/* Generated by Amaranth Yosys 0.25 (PyPI ver 0.25.0.0.post70, git sha1 e02b7f64b) */

(* \amaranth.hierarchy  = "top" *)
(* top =  1  *)
(* generator = "Amaranth" *)
module top(ovf, clk, rst, en);
  reg \$auto$verilog_backend.cc:2083:dump_module$2  = 0;
  (* src = "/home/parallels/github/learn-amaranth/upcounter/upcount.py:41" *)
  wire \$1 ;
  (* src = "/home/parallels/github/learn-amaranth/upcounter/upcount.py:47" *)
  wire [16:0] \$3 ;
  (* src = "/home/parallels/github/learn-amaranth/upcounter/upcount.py:47" *)
  wire [16:0] \$4 ;
  (* src = "/home/parallels/.local/lib/python3.10/site-packages/amaranth/hdl/ir.py:527" *)
  input clk;
  wire clk;
  (* src = "/home/parallels/github/learn-amaranth/upcounter/upcount.py:36" *)
  reg [15:0] count = 16'h0000;
  (* src = "/home/parallels/github/learn-amaranth/upcounter/upcount.py:36" *)
  reg [15:0] \count$next ;
  (* src = "/home/parallels/github/learn-amaranth/upcounter/upcount.py:32" *)
  input en;
  wire en;
  (* src = "/home/parallels/github/learn-amaranth/upcounter/upcount.py:33" *)
  output ovf;
  wire ovf;
  (* src = "/home/parallels/.local/lib/python3.10/site-packages/amaranth/hdl/ir.py:527" *)
  input rst;
  wire rst;
  assign \$1  = count == (* src = "/home/parallels/github/learn-amaranth/upcounter/upcount.py:41" *) 5'h19;
  assign \$4  = count + (* src = "/home/parallels/github/learn-amaranth/upcounter/upcount.py:47" *) 1'h1;
  always @(posedge clk)
    count <= \count$next ;
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$2 ) begin end
    \count$next  = count;
    (* src = "/home/parallels/github/learn-amaranth/upcounter/upcount.py:43" *)
    casez (en)
      /* src = "/home/parallels/github/learn-amaranth/upcounter/upcount.py:43" */
      1'h1:
          (* full_case = 32'd1 *)
          (* src = "/home/parallels/github/learn-amaranth/upcounter/upcount.py:44" *)
          casez (ovf)
            /* src = "/home/parallels/github/learn-amaranth/upcounter/upcount.py:44" */
            1'h1:
                \count$next  = 16'h0000;
            /* src = "/home/parallels/github/learn-amaranth/upcounter/upcount.py:46" */
            default:
                \count$next  = \$4 [15:0];
          endcase
    endcase
    (* src = "/home/parallels/.local/lib/python3.10/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \count$next  = 16'h0000;
    endcase
  end
  assign \$3  = \$4 ;
  assign ovf = \$1 ;
endmodule
